
# 服务端口配置
server:
  port: 8081  # 端口为 8081， 默认端口为 8080
  tomcat:
    uri-encoding: utf-8  # tomcat 字符集定义为 utf-8

# 日志相关配置
logging:
  level:
    root: info
    com.robin.springbootlearn.app.dao: debug
    com.robin.springbootlearn.app.service: trace
  config: classpath:logback-spring.xml
  file:
    name: ../logs/sb-learn.log  # 日志文件路径；如果不设置文件路径，默认在 root 路径下



